kind: Namespace
apiVersion: v1
metadata:
  name: tstapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jnative
  namespace: tstapp
  labels:
    app: jnative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jnative
  template:
    metadata:
      labels:
        app: jnative
    spec:
      containers:
        - name: jnative
          image: docker.io/dushyantsopra/jnative:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: jnative-client
  namespace: tstapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jnative
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jnative-client
  namespace: tstapp
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                port:
                  number: 8080
                name: jnative-client
            pathType: Prefix
            path: /
  ingressClassName: nginx
